# Generated by Django 3.0 on 2021-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_auto_20210407_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdata',
            name='pid',
        ),
        migrations.AlterField(
            model_name='newdata',
            name='mobile',
            field=models.IntegerField(default=9848281888),
        ),
        migrations.AlterField(
            model_name='usrrg',
            name='age',
            field=models.IntegerField(default=10, max_length=120),
        ),
    ]
