# Generated by Django 3.0 on 2021-04-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0004_auto_20210407_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdata',
            name='pid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.UsrRg'),
        ),
        migrations.AlterField(
            model_name='newdata',
            name='mobile',
            field=models.IntegerField(default=1234567899),
        ),
        migrations.AlterField(
            model_name='usrrg',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
